### ISSUE TITLE
callbacks can't be generator functions

### ISSUE THREAD

**Issue by jbrodriguez** [lostintangent/react-native-code-push-saga#5]
I thought I could 

``` javascript
spawn(codePushSaga, {codePushStatusDidChange: didChange})
```

where

``` javascript
function* didChange(status) {
    console.log(`status-${status}`)
}
```

and this would allow me to 

``` javascript
yield put(....)
```

within the didChange function.

But the didChange is never triggered. A normal function does get callled.

Any ideas on how to work around this ?

I'm having to drop the saga and use the codePush lifecycle hooks, then store.dispatch some action.

**Comment by geof90** [comment]
From what I understand about generators, calling the generator simply returns the iterator, the body isn't executed until the first call to `next()`.

Help me understand your use case. I assume you just want to dispatch an action every time the status changes? Why do you need to pass in a generator? Why can't it simply be a function?

**Comment by jbrodriguez** [comment]
I use codePush lifecycle hooks to notify the user there's a un update pending, so that they restart the app.

I need the callback to be a generator to do something like `yield put(updateAvailable())`, within.

A simple function couldn't call yield and probably with some trick you could reference a store instance, but at that point, it would probably be more idiomatic what I'm doing now, which is to store.dispatch from the root component.

**Comment by mike623** [comment]
similar question. How can I dispatch action in normal function

*EDIT*
Workaround: I reuse the `store` object which passed to `provider` in App class. and call store.dispatch() directly in `codePushStatusDidChange` and `codePushDownloadDidProgress`

**Comment by grahamlyus** [comment]
This is my solution, it could probably be added as a PR quite easily:

```
export default function* updateSaga () {
  if (!__DEV__) {
    logger.info('updateSaga started')

    // Inline eventChannel used by the codePushStatusDidChange callback
    let statusChangeEmitter
    const channel = eventChannel(emitter => {
      statusChangeEmitter = emitter
      return () => {
      }
    })

    const codePushStatusDidChange = (status: Number) => {
      statusChangeEmitter && statusChangeEmitter(status)
    }

    yield fork(saga, {
      delayByInterval: 10 * 60,
      delayByAction: HIDE_ONBOARDING,
      codePushStatusDidChange
    })

    const checkForUpdate = function* () {
      yield call(codePush.sync, {}, codePushStatusDidChange)
    }

    yield takeLatest(UPDATE_RELOAD, restart)
    yield takeLatest(CHECK_FOR_UPDATE, checkForUpdate)
    yield takeLatest(channel, statusDidChange)
  }
}
```

It uses an `eventChannel` and just emits the status from the callback. That way you can just `take` from the channel and `statusDidChange` can be a generator or regular function. If you have a handle to the redux store as @mike623 mentions, this is unnecessary.

I also take actions for manually invoking a `sync` and restarting the application.
